### ISSUE TITLE
Release often

### ISSUE THREAD

**Issue by muan** [muan/emojilib#76]
I need to streamline this process. Probably need to do some research into how other people do this. 

**UPDATE** Process currently:

1. Prebuild for `simplemap.json` and commit if needed
2. Update version number in `bower.json` and `package.json`
3. Commit changes
4. `git tag`
5. `git push --tags`
6. Create release on GitHub
7. `npm publish`

I wish these steps can be reduced to a button as we merge in tiny updates like keyword additions. :joy:

**Comment by danbovey** [comment]
I've been using this lib for a json list of emojis, but it'd be good if it was always up to date with latest Unicode releases. I've been researching the Unicode public data, so I might be able to help out with this.

I'm guessing by streamline the process, you mean actually build a process to keep this package up to date so that we can get new Unicode emojis imported automatically.

I'll see if I can rewrite `build.js` to grab the latest [EmojiSources](http://www.unicode.org/Public/UNIDATA/EmojiSources.txt) and build the JSON file from there.

**Comment by muan** [comment]
Ah sorry, I meant that I should cut a release and publish them on NPM more often. The [last release](https://github.com/muan/emojilib/releases) was in January. :/

> I've been using this lib for a json list of emojis, but it'd be good if it was always up to date with latest Unicode releases.

I don't think this library should be up to date with the latest Unicode releases as the emojis won't be supported by operating systems til a much later date. 🤔

**Comment by zeke** [comment]
@muan I'd be happy to help maintain this repo.

Here's an article I wrote on automated publishing to npm: zeke.sikelianos.com/npm-and-github-automation-with-heroku/ -- that approach might be overkill for `emojilib` though as the updates are not very frequent.

**Comment by axe312ger** [comment]
@muan i am pretty sure https://github.com/semantic-release/semantic-release can help u. The setup can be a little bit tricky, but I am willing to help if needed :)

**Comment by axe312ger** [comment]
@muan I got a build process ready, it also includes translation support.

It is written yet in ES5, makes it low on dependencies but the code is pretty much bloatet.

Should I push the PR like this or upgrade to ES6+Babel before I do it?

Personally I would love to use modern JS, I am just not sure if this exceeds the scope of this project.

Opinions?
